### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by shripad-jyothinath** [RisingOSS-devices/official#1]
## Device you want to apply for
```
Redmi Note 11 (spes)
```

## Device tree sources

```
https://github.com/shripad-jyothinath/device_xiaomi_spes
https://github.com/shripad-jyothinath/kernel_xiaomi_spes_header
https://github.com/shripad-jyothinath/vendor_xiaomi_spes
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RisingOSSpes/948
```

## Other ROM's you maintain officially or unofficially
```
none
```

## Bugs on unofficial build
```
Safety net, device not certified
```

## How long have you been building for?
```
4 months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
yes, since the kernel source released by Xiaomi is not stable
```

### Telegram username
```
@Shripad_Gamer
```

**Comment by manidweep** [comment]
The device trees looks fine as I compared it to the original tree from where it was taken, it was not a pickfest. But given the fact that he started his development in april of this year. I have some doubts regarding his ability to tackle new issues when there will be a huge update in regards to android versions which is expected to be soon.
Device Tree - some work is done
Kernel - Not much
Vendor - Not much

I checked the github as well for other repos, seems like he is maintaining other device as well such as River and Hotdogb
If they can maintain them properly, we can include those devices as well.
Note : He is currently working on ofox for his device, but didn't not check the credibility of that repo.

**Comment by shripad-jyothinath** [comment]
Other repos such as river and hotdog, are not maintained by and I do not have them in possession, only spes (Redmi note 11) is in my possesion currently. I did not look through kernel source since it was a header and not the actual kernel source, I've done some improvements that were needed in vendor, not much since it was already quite stable
