### ISSUE TITLE
New maintainer For POCO F1

### ISSUE THREAD

**Issue by Finnaib** [RisingOSS-devices/official#10]
## Device you want to apply for
```
Beryllium (POCO F1)
```

## Device tree sources

```
https://github.com/Finnaib/device_xiaomi_beryllium.git
https://github.com/Finnaib/device_xiaomi_sdm845-common.git
https://github.com/Finnaib/kernel_xiaomi_sdm845.git
https://github.com/Finnaib/vendor_xiaomi.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/finn_projects
https://t.me/finn_projects_support
```

## Other ROM's you maintain officially or unofficially
```
3
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
10 Months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Finnaib
```

**Comment by Finnaib** [comment]
@manidweep

**Comment by athizz2005** [comment]
Which all official roms u have ?

**Comment by Finnaib** [comment]
Currently all unofficial roms i have bliss and skylineui and droidxui

**Comment by athizz2005** [comment]
link for all of those released in global grp of ur device pls

**Comment by Finnaib** [comment]
> link for all of those released in global grp of ur device pls

Ok 
https://t.me/PocoPhoneGlobalUpdates/7523
https://t.me/PocoPhoneGlobalUpdates/7437
https://t.me/PocoPhoneGlobalUpdates/7370(i was previously officially co -maintainer for ricedroid poco F1 too)

**Comment by athizz2005** [comment]
from u releases it looks like u dont maintain a proper tree u are using Excraze (Shikhar) trees from long as the dt u submitted is hard reset and only bringup commit is there all the history is deleted from August 2023- November2023

**Comment by Finnaib** [comment]
Yes sir I do use his trees as since base since long time because at time of ricedroid we using that trees for ricedroid so i am using it again now

**Comment by athizz2005** [comment]
u did not answer my main question why was it hard reset

**Comment by Finnaib** [comment]
> u did not answer my main question why was it hard reset
Because that's was our old ricedroid period trees and after that our exam started so we not committed there

**Comment by athizz2005** [comment]
i would ask u to rebase it from lineageOS trees with some improvements then re-apply again later...(2 commits for official rising)
i have checked other repo in ur git none of the device works seems properly commited by you all are forks from other repos.

**Comment by Finnaib** [comment]
Ok  sir

**Comment by Finnaib** [comment]
> i would ask u to rebase it from lineageOS trees with some improvements then re-apply again later...(2 commits for official rising) i have checked other repo in ur git none of the device works seems properly commited by you all are forks from other repos.

It's already rebase from lineageos

**Comment by athizz2005** [comment]
i cant see a single commit by you except the bringup commit

**Comment by Finnaib** [comment]
> 

Sir because no need for extra commits now even lineageos beryllium u can't see it  any new commits after  1 November 2022
