### ISSUE TITLE
New maintainer for eqs (Motorola Edge 30 Ultra)

### ISSUE THREAD

**Issue by davigamer987** [RisingOSS-devices/official#11]
## Device you want to apply for
```
eqs (Motorola edge 30 ultra / Motorola X30 Pro)
```

## Device tree sources

```
https://github.com/davigamer987/device_motorola_eqs/tree/risingos
https://github.com/davigamer987/device_motorola_sm8475-common/tree/risingos
https://github.com/eqs-development/android_kernel_motorola_sm8475
https://gitlab.com/eqs-development/proprietary_vendor_motorola_sm8475-common
https://gitlab.com/eqs-development/proprietary_vendor_motorola_eqs
https://github.com/eqs-development/android_device_motorola_eqs-kernel

```

## Link to the platform where you have released your unofficial build
```

https://t.me/edge30ultraroms
```

## Other ROM's you maintain officially or unofficially
```
Only Doing RisingOS currently 
```

## Bugs on unofficial build
```
Clock Becomes slightly offset when qs is expanded 
```

## How long have you been building for?
```
Since Ricedroid 2.5, 1 Year (Old builds can be found at https://t.me/cringeromsoneplus )
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@davigamer987
```

**Comment by davigamer987** [comment]
Also, this device needs certain telephony injection patches for sms to properly work https://review.lineageos.org/q/topic:13-qcom-telephony-injection

**Comment by davigamer987** [comment]
Any updates yet?

**Comment by davigamer987** [comment]
Btw for the "How long have you been building for?" Question I only included how long I've been building rising, Total Build experience including other roms would be 3+ Years

**Comment by wh0dat** [comment]
> Any updates yet?

Hey,.. At least yours is under review! Trying to remain hopeful that risingOS devs will welcome us in soon.. Maybe they went on vacation since google is delaying september security patch and a14 for a bit longer.. =)

**Comment by davigamer987** [comment]
> > Any updates yet?
> 
> Hey,.. At least yours is under review! Trying to remain hopeful that risingOS devs will welcome us in soon.. Maybe they went on vacation since google is delaying september security patch and a14 for a bit longer.. =)

That's likely the case, maybe we'll have to wait until android 14

**Comment by davigamer987** [comment]
> Good day!
> 
> Your request for maintainership has been approved. To join the maintainer group on Telegram, we will be sending you an invitation link shortly. If you haven't provided an email during the application, please reply to this message with your preferred email address.
> 
> 🤖 Notice: This message is auto-generated. For additional support or inquiries, contact us at [[risingtechossofficial@gmail.com](mailto:risingtechossofficial@gmail.com)].
> 
> Best regards, [Rising Tech Open Source Software]

davimarchesiprimo@gmail.com
