### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by LouisG1977** [RisingOSS-devices/official#19]
## Device you want to apply for
Poco F3
Your device name and codename
Alioth

## Email address
luisgonzales272@gmail.com
For contact purposes

## Device tree sources
https://github.com/LouisG1977/device_xiaomi_alioth
https://github.com/GustavoMends/kernel_xiaomi_alioth
https://github.com/LouisG1977/vendor_xiaomi_alioth

## Link to the platform where you have released your unofficial build
```
https://t.me/RisingOsAlioth
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```

## Bugs on unofficial build
```
Not.
```

## How long have you been building for?
```
10 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
https://t.me/LuisG1977
Your Telegram username
```

**Comment by manidweep** [comment]
we already have a maintainer for alioth
