### ISSUE TITLE
New maintainer for Raven

### ISSUE THREAD

**Issue by Jrcable1** [RisingOSS-devices/official#20]
## Device you want to apply for
```Pixel 6 Pro
Your device name and codename
``` Raven

## Email address
```jrcable1@gmail.com
For contact purposes
```jrcable0@gmail.com

## Device tree sources
<![--](https://github.com/Jrcable1/android_device_google_raviole)
-->https://github.com/Jrcable1/android_device_google_raviole-kernel
https://github.com/Jrcable1/android_device_google_gs101
https://github.com/RisingTechOSS/android_vendor_rising
## Link to the platform where you have released your unofficial build
```
https://drive.google.com/drive/folders/1HyHvAmiwF5zdZv6xbXD5YXO6_AsUGR53
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Weeks/Months/Years
```
On and off for years. Started Raven on 09/01/2023
## SELinux status?
```
Enforcing/Permissive.
```
Default
## Are you using a prebuilt kernel? If yes, why?
```
Yes, included in rom
```

## Contact
### Telegram username
```jrcable2
Your Telegram username
```jrcable2

**Comment by Jrcable1** [comment]
If I need to add/edit above let me know.

**Comment by nivlafx** [comment]
Approved.

**Comment by Jrcable1** [comment]
So, what changed that caused this to need improvement once it was already approved? What do I need to fix/change?

**Comment by manidweep** [comment]
i dont see any much work that on you did on the device expect bringup on the tree which you forked from the lead's raviole repo, so yea i changed the assignee to myself since i am the handler for rising

**Comment by Jrcable1** [comment]
> i dont see any much work that on you did on the device expect bringup on the tree which you forked from the lead's raviole repo, so yea i changed the assignee to myself since i am the handler for rising

OK well cool, since Rising is rebasing to lineage, won't be an issue anymore. I'll upload my lineage trees and everything will be good

**Comment by manidweep** [comment]
also your telegram bio is false, you are not official 
I see you have not changed that since last time
any comment on that?

**Comment by Jrcable1** [comment]
> also your telegram bio is false, you are not official I see you have not changed that since last time any comment on that?

No need. Thanks for confirming this is about Albino

**Comment by manidweep** [comment]
why are you keeping your bio as official when you are clearly not yet?

**Comment by Jrcable1** [comment]
Actually, I WAS official, Read above, Alvin approved an you jumped in and said no. So, technically I was official and you decided to change that

**Comment by manidweep** [comment]
I can jump in cause im core and the official handler for the team
i dont see your work anywhere so i removed it
i had a valid reason to

**Comment by Jrcable1** [comment]
Well, like I said, I'll upload change everything to lineage and then no more issues

**Comment by Jrcable1** [comment]
And Lewd uses pixel 6, 6 pro and 6 uses same trees so we will always conflict

**Comment by manidweep** [comment]
the thing is last time i checked which was 6 months ago, your bio was official rising maintainer
just want to clear that part, why?

**Comment by manidweep** [comment]
> And Lead uses pixel 6, 6 pro and 6 uses same trees so we will always conflict

there is a thing known as branches?
you can clearly push to a different branch

**Comment by Jrcable1** [comment]
> the thing is last time i checked which was 6 months ago, your bio was official rising maintainer just want to clear that part, why?

Nope. I changed it, it was Rising raven maintainer. Its been raven maintainer  for awhile now. Read

**Comment by Jrcable1** [comment]
Then when Alvin approved, I changer it to official

**Comment by manidweep** [comment]
push your trees and ping here
ill check when possible

**Comment by Jrcable1** [comment]
Gotcha. Already working on it. I have not yet decided if I want to switch to lineage kernel or keep prebuilt kernel in source. Riding is optimized for either/or and Android 14 for some, forces full lto in kernel to build or errors will happen. Easily fixed by chnaging to THIN LTO in gki_defconfig but still...

**Comment by Jrcable1** [comment]
Messaged in telegram

**Comment by Jrcable1** [comment]
Updated trees

**Comment by Jrcable1** [comment]
Waiting on updated @manidweep

**Comment by manidweep** [comment]
i'm busy man, @Jrcable1 
this isnt my only job
ill get back to you

**Comment by Jrcable1** [comment]
@manidweep any update?

**Comment by Jrcable1** [comment]
Added to official/unofficial because I have now became official matrixx  ROM builder for the Samsung Galaxy Tab S6 lite Wifi
