### ISSUE TITLE
New maintainer for Poco F3 

### ISSUE THREAD

**Issue by ashutoshchettri** [RisingOSS-devices/official#21]
## Device you want to apply for
```
Poco F3 (alioth)
```

## Email address
```
eidoronp67@gmail.com
```
## Device tree sources

```
https://github.com/VipersTree-alioth/android_device_xiaomi_alioth
https://github.com/VipersTree-alioth/android_device_xiaomi_sm8250-common
https://github.com/VipersTree-alioth/android_vendor_xiaomi_sm8250-common
https://github.com/VipersTree-alioth/android_vendor_xiaomi_alioth
https://github.com/ashutoshchettri/android_kernel_xiaomi_alioth
```

## Link to the platform where you have released your unofficial build
```
Not released yet
```

## Other ROM's you maintain officially or unofficially
```
Halcyon and afterlife
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
t.me/Eidoron1
```

**Comment by athizz2005** [comment]
Good day!

Your request for maintainership has been approved. To join the maintainer group on Telegram, we will be sending you an invitation link shortly. If you haven't provided an email during the application, please reply to this issue with your preferred email address.

🤖 Notice: This message is auto-generated. For additional support or inquiries, contact us at [[risingtechossofficial@gmail.com](mailto:risingtechossofficial@gmail.com)].

Best regards,
AtharvaSwamy
