### ISSUE TITLE
New maintainer for Poco F3 

### ISSUE THREAD

**Issue by LouisG1977** [RisingOSS-devices/official#23]
## Device you want to apply for
```
Poco F3 (alioth)
```

## Email address
```
luisgonzales272@gmail.com
```

## Device tree sources
https://github.com/LouisG1977/device_xiaomi_alioth
https://github.com/GustavoMends/kernel_xiaomi_alioth
https://github.com/LouisG1977/vendor_xiaomi_alioth
```
## Link to the platform where you have released your unofficial build
```
Not released yet
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
15 years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```
## Contact
### Telegram username
```
t.me/LuisG1977
```

**Comment by manidweep** [comment]
we already have a maintainer for alioth

**Comment by LouisG1977** [comment]
Dont Habe Viper say me take it!!

**Comment by manidweep** [comment]
I dont see any work of yours in the git, no bringup or nothing

**Comment by LouisG1977** [comment]
Try Now..

**Comment by manidweep** [comment]
That is not the way to do a bringup also it seems like you are a beginner, unfortunately we cannot give you maintainership
