### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by asriadirahim** [RisingOSS-devices/official#25]
## Device you want to apply for
```
Google Pixel 2/walleye | Google Pixel 2XL/taimen
```

## Email address
```
asriadirahim03@gmail.com
```

## Device tree sources

```
https://github.com/arprojectstudio/device_google_walleye
https://github.com/arprojectstudio/device_google_taimen
https://github.com/arprojectstudio/device_google_wahoo
```
```
https://github.com/arprojectstudio/vendor_google_walleye
https://github.com/arprojectstudio/vendor_google_taimen
```
```
https://github.com/arprojectstudio/kernel_google_wahoo
```

## Link to the platform where you have released your unofficial build
```
https://t.me/arbuildupdate/247
```

## Other ROM's you maintain officially or unofficially
```
RisingOS Unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
4 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No
```

### Telegram username
```
@asriadirahim
```

**Comment by arkajitmondal** [comment]
> ## Device you want to apply for
> ```
> Realme X7 Max(RMX3031)
> ```
> 
> ## Email address
> ```
> asriadirahim03@gmail.com
> ```
> 
> ## Device tree sources
> 
> ```
> https://github.com/bananadroid-devices/device_google_taimen
> https://github.com/bananadroid-devices/vendor_google_taimen
> 
> https://github.com/bananadroid-devices/device_google_walleye
> https://github.com/bananadroid-devices/vendor_google_walleye
> 
> https://github.com/bananadroid-devices/device_google_wahoo
> https://github.com/bananadroid-devices/kernel_google_wahoo
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> https://t.me/Pixel2Chat/146346
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> BananaDroid
> ```
> 
> ## Bugs on unofficial build
> ```
> None
> ```
> 
> ## How long have you been building for?
> ```
> 3 Years
> ```
> 
> ## SELinux status?
> ```
> Enforcing
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> ```
> @asriadirahim
> ```
>

**Comment by nivlafx** [comment]
Welcome to RisingOS.

**Comment by nivlafx** [comment]
Welcome to RisingOS.
