### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by MNoxx74** [RisingOSS-devices/official#31]
## Device you want to apply for
```
Realme GT 5G (cupidr)
```

## Email address
```
ampam877@gmail.com
```

## Device tree sources

```
https://github.com/MNoxx74/android_device_realme_cupidr/tree/lineage-21.0
https://github.com/MNoxx74/android_device_oneplus_sm8350-common/commits/lineage-21.0/
https://github.com/MNoxx74/android_kernel_realme_sm8350
https://github.com/realme-GT-A14-Development/android_hardware_oplus/tree/14-qpr2
https://github.com/realme-GT-A14-Development/proprietary_vendor_oneplus_sm8350-common/tree/lineage-21
https://github.com/realme-GT-A14-Development/vendor_realme_cupidr
```

## Link to the platform where you have released your unofficial build
```
https://t.me/realmeGTnews_updates/86
```

## Other ROM's you maintain officially or unofficially
```
Project sakura (official) , Project Matrixx (official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/MNoxx74
```

**Comment by manidweep** [comment]
rejected

**Comment by RisenID** [comment]
Hey, sorry for the long wait. Before I proceed, are you still interested considering its been a few months since you applied
