### ISSUE TITLE
New maintainer for A51

### ISSUE THREAD

**Issue by cat658011** [RisingOSS-devices/official#34]
## Device you want to apply for
```
Samsung galaxy A51 aka a51, a515f
```

## Email address
```
cat658011@gmail.com
```

## Device tree sources

```
Device
https://github.com/Exynos9611Development/android_device_samsung_universal9611-common
https://github.com/Exynos9611Development/android_device_samsung_a51
Vendor
https://github.com/Exynos9611Development/android_vendor_samsung_a51
https://github.com/Exynos9611Development/android_vendor_samsung_universal9611-common
Kernel
https://github.com/Roynas-Android-Playground/kernel_samsung_universal9611
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Exynos9611Development/685
```

## Other ROM's you maintain officially or unofficially
```
LineageOS 21 UNOFFICIAL
```

## Bugs on unofficial build
```
VoLTE
```

## How long have you been building for?
```
2 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
cat65801
```

**Comment by Royna2544** [comment]
https://github.com/Exynos9611Development/android_device_samsung_universal9611-common/commit/9d4b172ed2e62bfa94cf14812650320f869b8e8c
He doesn't know what this prop even do.

**Comment by cat658011** [comment]
Bro think I not dev

**Comment by manidweep** [comment]
> Bro think I not dev

well, look at the commit you inserted even though u didn't even research before adding
