### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by EvilAnsh** [RisingOSS-devices/official#4]
## Device you want to apply for
```
Realme 6/6i(Indian)/6s/7/Narzo/Narzo 20 Pro/Narzo 30 4G (RM6785)
```

## Device tree sources

```
https://github.com/EvilAnsh/android_device_realme_RM6785
https://github.com/AbzRaider/android_kernel_realme_mt6785
https://github.com/realme-mt6785-devs/proprietary_vendor_realme
```

## Link to the platform where you have released your unofficial build
```
v1.3(https://t.me/rm6785/2126), v1.2.5(https://t.me/rm6785/2113) , v1.2(https://t.me/rm6785/2095)
```

## Other ROM's you maintain officially or unofficially
```
CherishOS (Official) , BananaDroid
```

## Bugs on unofficial build
```
Native video calling (ViLTE) and Voice over WiFi (VoWiFi)
```

## How long have you been building for?
```
1.5 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@EvilAnsh
```

**Comment by UltimateAnsh** [comment]
@manidweep

**Comment by EvilAnsh** [comment]
@manidweep

**Comment by athizz2005** [comment]
1.5 years and using someone else tree with some commits any justification? ur primary device?

**Comment by EvilAnsh** [comment]
@athizz2005 bruh, first of all it doesn't mentioned that "How long have you been building for this device", it tells that "How long have you been building for?" means in total including other devices.

**Comment by manidweep** [comment]
@minaripenguin @athizz2005 he hasnt been added yet in the group
also @EvilAnsh i wanted to ask, what are roms are u currently maintaining (officially and unofficially)?

**Comment by EvilAnsh** [comment]
@manidweep sir as I mentioned CherishOS (officially), I've dropped Banana as It's dead now. And risingTechOSS (Unofficially).
