### ISSUE TITLE
New maintainer for veux

### ISSUE THREAD

**Issue by alexandrusemina** [RisingOSS-devices/official#5]
## Device you want to apply for
```
Xiaomi Redmi Note 11 Pro 5G/ Poco X4 Pro 5g (veux)
```

## Device tree sources

```
https://github.com/alexandrusemina/device_xiaomi_veux.git
https://github.com/alexandrusemina/device_xiaomi_veux-kernel.git
https://gitlab.com/nnippon99/android_vendor_xiaomi_veux.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/alexbuilds/104
```

## Other ROM's you maintain officially or unofficially
```
Spark OS and Derpfest both of them Officialy 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2.5 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes. We currently got the kernel source from MiCode but we still ship with stock prebuilt kernel to avoid any further issues until the source is fully stable.
```

### Telegram username
```
t.me/semialex16
```

**Comment by alexandrusemina** [comment]
@eun0115

**Comment by manidweep** [comment]
@minaripenguin this guy has been screened by risen(former pe maintainer)
Check his trees, I'm okay with approving this guy
Waiting for your assessment
