### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RedLintu16** [RisingOSS-devices/official#55]
## Device you want to apply for
```
Google Pixel 8a
```

## Email address
```
redlintu16@gmail.com
```

## Device tree sources

```
https://github.com/RedLintu16/android_device_google_akita
https://github.com/RedLintu16/android_device_google_zuma
https://github.com/RedLintu16/android_device_google_gs-common
https://github.com/RedLintu16/android_device_google_gs201
https://github.com/RedLintu16/android_device_google_gs101
https://android.googlesource.com/device/google/akita-kernel/ (I used the prebuilt kernel directly from Google)
https://github.com/TheMuppets/proprietary_vendor_google_akita
```

## Link to the platform where you have released your unofficial build
```
https://drive.google.com/file/d/1g90q41UPs6Nx-1kuSJZ3MbbfTDl3_DM2/view?usp=sharing
```

## Other ROM's you maintain officially or unofficially
```
None at the moment.
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, that's how LineageOS does it too.
```

### Telegram username
```
RedLintu16
```

**Comment by manidweep** [comment]
you say, you have been building for years
can you show where you have posted the builds?

**Comment by RedLintu16** [comment]
I used to build for the OnePlus 9 back in the day. I'll link my XDA below. 

https://xdaforums.com/m/red-prez16.10551569/#recent-content

Even built Rising for the OnePlus 9 Pro too. Well, it was called Rice back then, but you get the idea.

**Comment by manidweep** [comment]
https://github.com/RedPrez16, thats the account linked with the trees
is this yours?
if yes, then why did u give a different one for the application

**Comment by RedLintu16** [comment]
I got locked out of that account. So I had to make a new one.

**Comment by RedLintu16** [comment]
Only reason why I did that. Other than that, I would've used that account. Man I hated GitHub for forcing two factor on me and I still do now.

**Comment by manidweep** [comment]
> I got locked out of that account. So I had to make a new one.

if you got locked, im sure you could recover it

**Comment by RedLintu16** [comment]
No, as I didn't have any recovery method. I didn't have access to the phone number anymore or any of the backup codes. Or anything like that. I'm sorry for the confusion!

**Comment by RedLintu16** [comment]
Do I make the cut?

**Comment by RisenID** [comment]
Hey, thanks for the application. However since applications for A14 are closed, your application is denied. Please feel free to apply again in the future, once A15 sources from us release, and once you have more experience under your belt.
