### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by samrth012** [RisingOSS-devices/official#57]
## Device you want to apply for
```
Nothing Phone 2 (Pong)
```

## Email address
```
samrth012@gmail.com
```

## Device tree sources

```
https://github.com/samrth012/android_device_nothing_Pong/tree/rising-rb
https://gitlab.com/samrth012/android_vendor_nothing_Pong.git
https://github.com/samrth012/kernel_nothing_sm8475-meteoric.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/NothingPhone2/411287
https://t.me/NothingPhone2/414057
https://t.me/NothingPhone2/417251
```

## Other ROM's you maintain officially or unofficially
```
PixelOS (Unofficial - applied for official)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1.5-2 years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
samrth012
```

**Comment by manidweep** [comment]
cannot be given official status as of now

**Comment by samrth012** [comment]
> cannot be given official status as of now

Sir, can I know the reasons for that so i can fixup any issues if its on my end.

**Comment by manidweep** [comment]
https://github.com/samrth012/android_device_nothing_Pong/commit/2a13c5493c519a451734640c08eae7f9eac8e72c

what does this even do with no changes at all?

**Comment by samrth012** [comment]
> [samrth012/android_device_nothing_Pong@2a13c54](https://github.com/samrth012/android_device_nothing_Pong/commit/2a13c5493c519a451734640c08eae7f9eac8e72c)
> 
> what does this even do with no changes at all?

I messed that commit, i did so many cherry-pick while rebasing that i forgot to check that, sorry for that, but the commit changes are already there in the tree and that commit was not needed as such will delete it, thanks for the help.

Anything else that is concerning sir ?

**Comment by manidweep** [comment]
want to know when you have started your development in rising for pong

**Comment by samrth012** [comment]
> want to know when you have started your development in rising for pong

I was doing it initially with my friend, then i completely took over since last two builds. 
First release was on 23/07/2024 ( v4.0 )

**Comment by manidweep** [comment]
so it was a month ago,why did u use a two months old tree when there were better ones available?
just that

**Comment by samrth012** [comment]
> so it was a month ago,why did u use a two months old tree when there were better ones available? just that

I prefer dolby over dirac and new ones have dirac as base and picking up dolby in that is causing a lot of trouble, that we are unable to figure out (all the devs). 
And it already have proper working glyph and powershare, they added it very recently and still is not completely perfect yet ( and from my discussion users need proper glyph and powershare so its a plus for stability and user preference.
Also I will be updating all the necessary things from the new ones.

**Comment by samrth012** [comment]
> nice, you are too early for official tho so wait

Ok, can I know estimate when I should apply again.

Also just for reference, the trees are very stable and completely bugless, haven't received any report or problem from any single user yet ( this was one of the reason I applied so early )
