### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by r0ddty** [RisingOSS-devices/official#59]
## Device you want to apply for
```
Redmi 10C/10 India/10 Power - fog/rain/wind
```

## Email address
```
r0d@ukr.net
```

## Device tree sources

```
https://github.com/r0ddty/device_xiaomi_fog
https://github.com/r0ddty/kernel_xiaomi_fog
https://github.com/r0ddty/vendor_xiaomi_fog
```

## Link to the platform where you have released your unofficial build
```
https://t.me/TheProjectC
```

## Other ROM's you maintain officially or unofficially
```
BlissROMs unofficially
```

## Bugs on unofficial build
```
None in ROM itself, only OSS kernel ones(DT2W on focaltech touch panels and fingerprint gestures on some variants of device)
```

## How long have you been building for?
```
3 months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@stoplookmynick
```

**Comment by manidweep** [comment]
wondering if you ever bothered to give authorship to any of your commits?

**Comment by r0ddty** [comment]
> wondering if you ever bothered to give authorship to any of your commits?

I dont really understand what do you mean by that, i always include link to original commit when taking it from some other repo, should i include --author flag as well, when commiting changes from other repos?

**Comment by manidweep** [comment]
https://github.com/r0ddty/kernel_xiaomi_fog/commit/464a0331b65e055610d9e67309f2d8ea1e2293bf
cannot see for this one

> > wondering if you ever bothered to give authorship to any of your commits?
> 
> I dont really understand what do you mean by that, i always include link to original commit when taking it from some other repo, should i include --author flag as well, when commiting changes from other repos?

**Comment by r0ddty** [comment]
> [r0ddty/kernel_xiaomi_fog@464a033](https://github.com/r0ddty/kernel_xiaomi_fog/commit/464a0331b65e055610d9e67309f2d8ea1e2293bf) cannot see for this one
> 
> > > wondering if you ever bothered to give authorship to any of your commits?
> > 
> > 
> > I dont really understand what do you mean by that, i always include link to original commit when taking it from some other repo, should i include --author flag as well, when commiting changes from other repos?

Oh, i am so sorry about it, just rebased commits propertly

**Comment by RisenID** [comment]
Hey, just wanting to clear up some discrepancies that im seeing, how many roms are you actually working on, because im seeing up to date branches for 4-5 other roms in your trees. Further, you say no bugs in the rom, but there are bugs in the oss kernel. Is this the same kernel you are shipping with the rom?

**Comment by RisenID** [comment]
Additionally, i see the point raised earlier hasnt been resolved with commits such as 
https://github.com/r0ddty/kernel_xiaomi_fog/commit/dc5fd529c0891fac8690410bead9b14d0a199a81
and 
https://github.com/r0ddty/kernel_xiaomi_fog/commit/123466d4f826193f97dfa487bcf498ad0276505f
still not having proper authorship, and thats just on the first page.

**Comment by r0ddty** [comment]
Hello, yeah, i have a few branches in device tree repo as i was learning when building other ROMs, but since then i am maintaining only two ROMs which are rising and bliss
Also, yeah, these two kernel bugs(one of them is fixable with magisk/KSU module) are appearing in open-source kernel because it is incomplete as developers made it by themselves based on spes kernel source as fog one is not yet published by OEM
About authorship - i included links to original files, and at the point of time while i was working on it i absolutely forget about --author parameter, i am including author name in all commits by other authors now

**Comment by RisenID** [comment]
Thanks for the application, and im glad to see your willingness to improve, however with a15 launch just around the corner and major changes coming with that, i must deny your application this time. Pleaae feel free to apply again in a couple months when your a15 code is ready.
