### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Badr98-t** [RisingOSS-devices/official#6]
## Device you want to apply for
realme GT NEO2
Your device name and codename
realme GT NEO2 (bitra)

## Device tree sources

```
https://github.com/VEN0M98/device_realme_bitra
https://github.com/VEN0M98/device_realme_sm8250
https://github.com/VEN0M98/vendor-realme-bitra
https://github.com/VEN0M98/vendor_realme_sm8250
```

## Link to the platform where you have released your unofficial build
```
not released since with test results  there are some source side bugs 
```

## Other ROM's you maintain officially or unofficially
```
black iron on kebab```
```

## Bugs on unofficial build
```
Laggy using wallpaper and style section,
```

## How long have you been building for?
```
1.6 yrs
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/VEN0M98
```

**Comment by athizz2005** [comment]
U have been building for 1.6 years then too using someone else tree that too not even rebased? just did bringup and some commits here and there?

**Comment by Badr98-t** [comment]
Better to do a bring up and test all by my self than have a rebased tree and have nothing work

**Comment by athizz2005** [comment]
hmm lets see
