### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by hasan6034** [RisingOSS-devices/official#61]
## Device you want to apply for
```
Redmi 10/2022/Prime Redmi Note 11 4G (selene,selenes,eos)
```

## Email address
```
hasanbasrioy@gmail.com
```

## Device tree sources

```
https://github.com/hasan6034/android_device_xiaomi_selene
https://github.com/25ji-Telegram-de/android_kernel_xiaomi_selene
https://github.com/hasan6034/android_vendor_xiaomi_selene
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Redmi10_Community/199312
```

## Other ROM's you maintain officially or unofficially
```
UNOFFICIAL LİST
crDroid
Pixel OS
AlphaDroid
Project Matrixx
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
10 months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
hasan6034
```

**Comment by manidweep** [comment]
Unfortunately, due to your high number of roms
Your application is rejected for now
