### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by finish0314** [RisingOSS-devices/official#62]
## Device you want to apply for
```
Redmi K60/POCO F5 Pro (mondrian)
```

## Email address
```
finish21190@gmail.com
```

## Device tree sources

```
https://github.com/finish0314/device_xiaomi_mondrian
https://github.com/finish0314/vendor_xiaomi_mondrian
https://github.com/cupid-development/android_kernel_xiaomi_sm8450
https://github.com/finish0314/device_xiaomi_sm8450-common

```

## Link to the platform where you have released your unofficial build
```
https://www.cyuit.cn/?p=149
```

## Other ROM's you maintain officially or unofficially
```
No,only RisingOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
One years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
t.me/finish0314
```

**Comment by manidweep** [comment]
why is your github so new then?
if you say 1 year?

**Comment by finish0314** [comment]
> why is your github so new then? if you say 1 year?

Because github is not easy to connect to in China, I use the git website in China

**Comment by RisenID** [comment]
Hey, in regards to the kernel, are you using the one linked or are there any modifications from your end as well?

**Comment by finish0314** [comment]
> 嘿，关于内核，您使用的是链接的内核还是您的版本也进行了任何修改？

linked kernel, which I didn't make separate modifications

**Comment by finish0314** [comment]
> Hey, in regards to the kernel, are you using the one linked or are there any modifications from your end as well?

linked kernel, which I didn't make separate modifications

**Comment by RisenID** [comment]
Thanks for your application, but with android 15 dropping next month, i dont feel comfortable about commiting to any new maintainer. However, i dont see much issues with your code, and would be glad to review your application once you have android 15 working well.

**Comment by finish0314** [comment]
> Thanks for your application, but with android 15 dropping next month, i dont feel comfortable about commiting to any new maintainer. However, i dont see much issues with your code, and would be glad to review your application once you have android 15 working well.

ok
