### ISSUE TITLE
New maintainer Garnet RisingOS

### ISSUE THREAD

**Issue by chuspita** [RisingOSS-devices/official#63]
## Device you want to apply for
```
Xiaomi Redmi Note 13 Pro (Garnet)
```

## Email address
```
kosecki99@gmail.com
```

## Device tree sources

```
https://github.com/Garnet-Lab/device_xiaomi_garnet
https://github.com/Garnet-Lab/kernel_xiaomi_horus
https://github.com/Garnet-Lab/vendor_xiaomi_garnet
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
InfinityX, AfterlifeOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 or 4 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, The Micode kernel is incomplete, and for the moment we use the prebuilt kernel, although I am inserting my own commits.
```

### Telegram username
```
https://t.me/franlop77
```

**Comment by RisenID** [comment]
Hey, thanks for the application. However due to the fact that your trees are private or the links provided are incorrect, I must deny your application this time. Please feel free to apply again in the future.
