### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by onesmiledx** [RisingOSS-devices/official#66]
## Device you want to apply for
```
Samsung Galaxy A71 4G (a71)
```

## Email address
```
beksultanbazuov@gmail.com
```

## Device tree sources

```
https://github.com/onesmiledx/android_device_samsung_a71
https://github.com/LineageOS/android_device_samsung_a71-common
https://github.com/LineageOS/android_kernel_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71-common
```

## Link to the platform where you have released your unofficial build
```
https://xdaforums.com/t/rom-14-0-unofficial-stable-20240820-risingos-5-0-for-samsung-galaxy-a71-4g-ss-ds.4687837/
https://t.me/starlixx/201
https://github.com/onesmiledx/crave_aosp_builder/releases/tag/10462553312
```

## Other ROM's you maintain officially or unofficially
```
PixelOS and CherishOS
```

## Bugs on unofficial build
```
VoLTE
```

## How long have you been building for?
```
3 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@starlixpon
```

**Comment by RisenID** [comment]
Hey,
Im failing to see what your contribution to that code is, since you are straight away using lineageos trees with no modifications made by you at all.

**Comment by onesmiledx** [comment]
> Hey, Im failing to see what your contribution to that code is, since you are straight away using lineageos trees with no modifications made by you at all.

edited, sorry

**Comment by RisenID** [comment]
Thanks for your application, but due to the low number of commits that you have contributed towards the code, I'm unable to determine whether or not you would be a good fit for us, I have to deny your application this time.
Please feel free to apply again when you have more experience and more work under your belt.
