### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ksawlii** [RisingOSS-devices/official#67]
## Device you want to apply for
```
Name: Samsung Galaxy S10
Codename: beyond1lte
```

## Email address
```
ksawery.blaszczak@proton.me
```

## Device tree sources

```
device:
https://github.com/LineageOS/android_device_samsung_beyond1lte.git
https://github.com/LineageOS/android_device_samsung_exynos9820-common.git
https://github.com/linux4-bringup-priv/android_device_samsung_slsi_sepolicy.git

vendor:
https://github.com/linux4-bringup-priv/android_vendor_samsung_beyond1lte.git
https://github.com/linux4-bringup-priv/android_vendor_samsung_exynos9820-common.git 

kernel:
https://github.com/LineageOS/android_kernel_samsung_exynos9820.git 

hardware:  
https://github.com/LineageOS/android_hardware_samsung.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi_libbt.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi_scsc_wifibt_wpa_supplicant_lib.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi_scsc_wifibt_wifi_hal.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_interfaces.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_exynos.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_graphics.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_openmax.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_exynos5.git
https://github.com/linux4-bringup-priv/android_hardware_samsung_slsi-linaro_config.git
```

## Link to the platform where you have released your unofficial build
```
https://xdaforums.com/t/rom-14-unofficial-rising-os-5-0-v2-beta-stable-s10.4685385/ 
```

## Other ROM's you maintain officially or unofficially
```
None (for now)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 Months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Ksawlii
```

**Comment by RisenID** [comment]
Hey, 
Im failing to see what your contribution to that code is, since you are straight away using linux4's work with no modifications made at all.

**Comment by Ksawlii** [comment]
> Hey, 
> Im failing to see what your contribution to that code is, since you are straight away using linux4's work with no modifications made at all.

His trees work good without bugs so i am not changing anything

**Comment by RisenID** [comment]
Thanks for your application, but due to me not being able to see your work to determine whether or not you would be a good fit for us, I have to deny your application this time.
Please feel free to apply again when you have more experience and more work under your belt.
