### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by DeandraAir** [RisingOSS-devices/official#68]
## Device you want to apply for
```
Poco M5 4G / Redmi 11 Prime 4G (rock/stone).
```

## Email address
```
affaantuh407@gmail.com
```

## Device tree sources

```
https://github.com/DeandraAir/android_device_xiaomi_rock
https://github.com/DeandraAir/kernel_xiaomi_rock-prebuilts
https://github.com/DeandraAir/vendor_xiaomi_rock
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoM5IDC/226
```

## Other ROM's you maintain officially or unofficially
```
EvolutionX & AwakenOS (unofficial).
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 Years.
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
yes, because there are no kernel sources yet.
```

### Telegram username
```
 @DeanPerformer
```

**Comment by RisenID** [comment]
Hey, any reason for this?
https://github.com/DeandraAir/android_device_xiaomi_rock/commit/ebe228db52b668782f0d371e339e8f692f196106

**Comment by DeandraAir** [comment]
for delete unwanted apps because many user not need it

**Comment by DeandraAir** [comment]
> Hey, any reason for this? [DeandraAir/android_device_xiaomi_rock@ebe228d](https://github.com/DeandraAir/android_device_xiaomi_rock/commit/ebe228db52b668782f0d371e339e8f692f196106)

for delete unwanted apps because many user not need it

**Comment by RisenID** [comment]
> > Hey, any reason for this? [DeandraAir/android_device_xiaomi_rock@ebe228d](https://github.com/DeandraAir/android_device_xiaomi_rock/commit/ebe228db52b668782f0d371e339e8f692f196106)
> 
> for delete unwanted apps because many user not need it

We already have multiple flags (around 3) for different levels of gapps to be included in the build. Why not use one of those?

**Comment by DeandraAir** [comment]
> > > Hai, ada alasan untuk ini? [DeandraAir/android_device_xiaomi_rock@ebe228d](https://github.com/DeandraAir/android_device_xiaomi_rock/commit/ebe228db52b668782f0d371e339e8f692f196106)
> > 
> > 
> > untuk menghapus aplikasi yang tidak diinginkan karena banyak pengguna tidak membutuhkannya
> 
> Kami sudah memiliki beberapa flag (sekitar 3) untuk berbagai level gapps yang akan disertakan dalam build. Mengapa tidak menggunakan salah satunya?

I want to provide a flexible ROM for users who don't want to depend on certain GApps. This allows them to select and install applications according to their needs.

**Comment by RisenID** [comment]
> > > > Hai, ada alasan untuk ini? [DeandraAir/android_device_xiaomi_rock@ebe228d](https://github.com/DeandraAir/android_device_xiaomi_rock/commit/ebe228db52b668782f0d371e339e8f692f196106)
> > > 
> > > 
> > > untuk menghapus aplikasi yang tidak diinginkan karena banyak pengguna tidak membutuhkannya
> > 
> > 
> > Kami sudah memiliki beberapa flag (sekitar 3) untuk berbagai level gapps yang akan disertakan dalam build. Mengapa tidak menggunakan salah satunya?
> 
> I want to provide a flexible ROM for users who don't want to depend on certain GApps. This allows them to select and install applications according to their needs.

This is already what the gms core flag, vanilla build flag, full gapps build flag and corge gapps with some more extras are for. Why use removepackages to remove so many apps rather than just using the core gapps flag?

**Comment by RisenID** [comment]
This isnt making any sense to me, if you want a vanilla build, just dont use the dms flag. If you want only basic gapps use the gms core flag, if you want more than that, use gms core and gms core extra flag and if you want all gapps, use gms flag. There is absolutely no need for remove packages.

**Comment by DeandraAir** [comment]
> This isnt making any sense to me, if you want a vanilla build, just dont use the dms flag. If you want only basic gapps use the gms core flag, if you want more than that, use gms core and gms core extra flag and if you want all gapps, use gms flag. There is absolutely no need for remove packages.

The Poco M5 only has a 4GB RAM variant. If I only build the core build, the size is still quite large and feels heavy for multitasking because your RAM is narrow. If I build vanilla, then they have to do RW first, so that's why we use removePackage. I will revert it if this is not allowed in RisingOS

**Comment by RisenID** [comment]
Hey, thanks for the application. However since applications for A14 are closed, your application is denied. Please feel free to apply again in the future, once A15 sources from us release, and once you have more experience under your belt.
