### ISSUE TITLE
New maintainer for TECNO POVA 4 Pro

### ISSUE THREAD

**Issue by Shirayuki39** [RisingOSS-devices/official#70]
## Device you want to apply for
```
TECNO POVA 4 Pro(LG8n)
```

## Email address
```
lorddemecrius83@proton.me
```

## Device tree sources

```
https://github.com/Anything-at-25-00/android_device_tecno_LG8n/tree/rising-14
https://github.com/Anything-at-25-00/device_tecno_lg8n_kernel
https://github.com/Anything-at-25-00/android_vendor_tecno_LG8n
```

## Link to the platform where you have released your unofficial build
```
https://t.me/shirayuki428stuff/453
```

## Other ROM's you maintain officially or unofficially
```
DerpFest - Unofficial
BlissRom - Unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
8 Years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes, due to no proper kernel source, only GKI
```

### Telegram username
```
@shirayuki_428
```

**Comment by RisenID** [comment]
Hey, please could you tell me why some of your unofficial builds ship with root?

**Comment by Shirayuki39** [comment]
> Hey, please could you tell me why some of your unofficial builds ship with root?

Mostly for user convenience, though I'd replace the kernel with a non-KSU kernel if that's not allowed

**Comment by RisenID** [comment]
Please reach out to me at @RisenID on telegram to discuss the next steps. Closing this issue as completed for now.
