### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Gtajisan** [RisingOSS-devices/official#74]
## Device you want to apply for
```
Redmi 7A/8/8A/8A Dual unified  code name (SDM439)
```

## Email address
```
ffjisan804@gmail.com
```

## Device tree sources

```
<-- device tree mi439 -- >
https://github.com/Gtajisan/device_xiaomi_mi439/tree/RisingOS
<-- kernel mi439-4.19 -- >
https://github.com/Jprimero15/android_kernel_xiaomi_sdm439-4.19
<-- vendor mi439-4.19 -- >
https://github.com/LOLZKERNEL/proprietary_vendor_xiaomi_mi439-4.19
```

## Link to the platform where you have released your unofficial build
```
https://t.me/farhan_build/396
```

## Other ROM's you maintain officially or unofficially
```
All - unofficial - (Alpha droid, matrixx os, Afterlife, project blaze )
```

## Bugs on unofficial build
```
( RisingOS) - In vanilla build, the settings search bar will be broken.
```

## How long have you been building for?
```
6 months 
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### telegram 
```
@FARHAN_MUH_TASIM
```

**Comment by RisenID** [comment]
Hey, thanks for the application. However looking at your work and the fact that applications for A15 are close, your application is denied. Please feel free to apply again in the future, once A15 sources from us release, and once you have more experience under your belt.

**Comment by Gtajisan** [comment]
Thanks for reply.

**Comment by Gtajisan** [comment]
Btw sir I want 5.2 mainteship 😿💔.
