### ISSUE TITLE
New maintainer for Galaxy A71

### ISSUE THREAD

**Issue by eun0115** [RisingOSS-devices/official#77]
## Device you want to apply for
```
Galaxy A71 
```

## Email address
```
gianpaoloestacio5@gmail.com
```

## Device tree sources

```
https://github.com/eun0115/android_device_samsung_a71
https://github.com/eun0115/android_device_samsung_a71-common
https://github.com/eun0115/android_kernel_samsung_a71-common
```

## Link to the platform where you have released your unofficial build
```
None
```

## Other ROM's you maintain officially or unofficially
```
Derpfest
```

## Bugs on unofficial build
```
Volte 
```

## How long have you been building for?
```
3 years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
eun0115
```

**Comment by eun0115** [comment]
accept if A15 is nearby, ty

**Comment by hipexscape** [comment]
Probably wait for stable risingOs A15

**Comment by eun0115** [comment]
> Probably wait for stable risingOs A15

sar wen

**Comment by hipexscape** [comment]
> > Probably wait for stable risingOs A15
> 
> sar wen

Release unofficial build sir

**Comment by hipexscape** [comment]
Hey @eun0115,

There is already a maintainer for for device.

- Ref to: https://t.me/RisingOS_news/1474

Regards,
@hipexscape
On behalf of RisingOs team.
