### ISSUE TITLE
New maintainer for Ginkgo

### ISSUE THREAD

**Issue by Miracleprjkt** [RisingOSS-devices/official#78]
## Device you want to apply for
```
Redmi Note 8 - Ginkgo
```

## Email address
```
Miraclev1@proton.me
```

## Device tree sources

```
https://github.com/Miracleprjkt/device_xiaomi_ginkgo
https://github.com/Miracleprjkt/android_kernel_xiaomi_ginkgo
https://github.com/Miracleprjkt/vendor_xiaomi_ginkgo
```

## Link to the platform where you have released your unofficial build
```
https://github.com/Miracleprjkt/Release
```

## Other ROM's you maintain officially or unofficially
```
-
```

## Bugs on unofficial build
```
-
```

## How long have you been building for?
```
one years
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Miraclesupremacy
```

**Comment by hipexscape** [comment]
Probably wait for stable risingOs A15
