### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by rik-x777** [RisingOSS-devices/official#79]
## Device you want to apply for
```
poco f4 (munch)
```

## Email address
```
aritrarik536@protonmail.com
```

## Device tree sources

```
https://github.com/rik-x777/android_device_xiaomi_munch
https://github.com/rik-x777/android_device_xiaomi_sm8250-common.git
https://github.com/LineageOS/android_kernel_xiaomi_sm8250.git
https://github.com/rik-x777/proprietary_vendor_xiaomi_munch.git
https://github.com/rik-x777/proprietary_vendor_xiaomi_sm8250-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoF4updates/1205
```

## Other ROM's you maintain officially or unofficially
```
crdroid officially and pixelstar officially
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@rik_x290
```

**Comment by hipexscape** [comment]
Will be processed once RisingOs A15 will be stable

**Comment by rik-x777** [comment]
any approx ETA?

**Comment by hipexscape** [comment]
Hello @rik-x777,

While checking the trees mentioned in the application, few authorship issues I've pointed out. For your convenience, I'll enlist those here.

- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/a7f22cd74f92aba3315ef8718580065af4754a0a
- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/336fe025907b569c8ad4503d8950a427351e9f42
- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/336fe025907b569c8ad4503d8950a427351e9f42
- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/57f8f2e4d8682006a1ba6df9133ef83dd2af6fb5
- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/acdc2b0b65e330ddb26c018e32f6c4ec2b38d2af
- https://github.com/rik-x777/android_device_xiaomi_sm8250-common/commit/c2342967099284eaac70445ba1315c600519e504

Please revise the issues and update us as soon as possible.

Regards,
@hipexscape 
On behalf of RisingOs Team.

**Comment by RisenID** [comment]
Hey, took a look at your trees, and i see multiple issues with it. Some of them being the absolute lack of vendor history, multiple commits without any authorship, and in some cases commits to undo changes on the next immediate day. 
Due to this and many other issues, i do not feel that you are a good fit for now. This may change in the future though, and please feel free to apply again when you have more experience.
