### ISSUE TITLE
New maintainer for Xiaomi Pocophone F1

### ISSUE THREAD

**Issue by Legendleo90** [RisingOSS-devices/official#8]
## Device you want to apply for
```
Xiaomi Pocophone F1 (beryllium)
```

## Device tree sources

```
https://github.com/Legendleo90/rising_xiaomi_beryllium
https://github.com/Legendleo90/kernel_xiaomi_beryllium
https://github.com/Legendleo90/rising_vendor_beryllium
```

## Link to the platform where you have released your unofficial build
```
https://t.me/PocoPhoneGlobalUpdates/7551 (1.3)
```

## Other ROM's you maintain officially or unofficially
```
Alphadroid/PixysOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
8 months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Legendleo90
```

**Comment by Legendleo90** [comment]
@manidweep

**Comment by risingtechopensourcesoftware** [comment]
Good day!

Your request for maintainership has been approved. To join the maintainer group on Telegram, we will be sending you an invitation link shortly. If you haven't provided an email during the application, please reply to this message with your preferred email address.

🤖 Notice: This message is auto-generated. For additional support or inquiries, contact us at [[risingtechossofficial@gmail.com](mailto:risingtechossofficial@gmail.com)].

Best regards,
[Rising Tech Open Source Software]

**Comment by Legendleo90** [comment]
> Good day!
> 
> Your request for maintainership has been approved. To join the maintainer group on Telegram, we will be sending you an invitation link shortly. If you haven't provided an email during the application, please reply to this message with your preferred email address.
> 
> 🤖 Notice: This message is auto-generated. For additional support or inquiries, contact us at [[risingtechossofficial@gmail.com](mailto:risingtechossofficial@gmail.com)].
> 
> Best regards, [Rising Tech Open Source Software]

Thanks for your time
Here is my email address-: akshatleo9456@gmail.com
