### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by swiitchOFF** [RisingOSS-devices/official#81]
## Device you want to apply for
```
Device - Xiaomi 11T Pro (vili)
```
## Email address
```
Email - iamswiitchoff@gmail.com
```

## Device tree sources
```
1) https://github.com/Spanish-or-Vanish/device_xiaomi_vili/tree/fifteen
2) https://github.com/Spanish-or-Vanish/android_device_xiaomi_sm8350-common
3) https://github.com/swiitch-OFF-Lab/vendor_xiaomi_vili
4) https://github.com/Spanish-or-Vanish/vendor_xiaomi_sm8350-common/tree/A15
5) https://github.com/swiitch-OFF-Lab/kernel_xiaomi_sm8350
```

## Link to the platform where you have released your unofficial build
```
https://t.me/swiitchOFF_updates/1449
```

## Other ROM's you maintain officially or unofficially
```
Official crDroid, unofficial Paranoid Android 
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Since 2022
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
```
@MIUI_users_r_GAY
```

**Comment by manidweep** [comment]
we don't allow maintainers who maintain more than 3 roms,
you seems to have already do more than 3 as far as i can tell from your channel

**Comment by swiitchOFF** [comment]
It was for A14 EOL and on A15 only cr is currently

**Comment by RisenID** [comment]
> It was for A14 EOL and on A15 only cr is currently

In your application you say you are maintaining 2 roms, further with the current state of roms on a15, we have no assurance that you wont maintain more once more roms bring a15 sources. Feel free to apply in a couple months, if you indeed do maintain less roms, and instead focus on properly supporting what you build.
