### ISSUE TITLE
New maintainer for Alioth

### ISSUE THREAD

**Issue by Sanjivns** [RisingOSS-devices/official#83]
## Device you want to apply for
```
Poco F3 / Mi 11X / Redmi K40 (alioth)
```

## Email address
```
alshahab109@gmail.com
```

## Device tree sources

```
https://github.com/Sanjivns/device_xiaomi_alioth
https://github.com/Sanjivns/vendor_xiaomi_alioth
https://github.com/Sanjivns/device_xiaomi_sm8250-common
https://github.com/Sanjivns/vendor_xiaomi_sm8250-common
https://github.com/EmanuelCN/kernel_xiaomi_sm8250
```

## Link to the platform where you have released your unofficial build
```
https://t.me/SanjisRoms/38
```

## Other ROM's you maintain officially or unofficially
```
ProjectBlaze Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
9 Months
```

## SELinux status?
```
Enforcing
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@sanjivns
```

**Comment by tanvirr007** [comment]
sanji pero dev of alioth/in and handsome 🥰🌹

**Comment by manidweep** [comment]
your applications is a no from my side,
it seems you dont know how to do branches since u based on official blaze trees which is from evolution x based in the first place

**Comment by RisenID** [comment]
Hey, after taking a look at your stuff, I definitely see some good things, but i also have a few things that I dont like or find unecessary.
https://github.com/Sanjivns/device_xiaomi_alioth/commit/5150b57e11bce5419631be92efcfe8de9904872c
really isnt great, just clone your keys to lineage-priv in vendor.
For now I will also have to reject your application, but please do feel free to apply again in the future, when you have more experience.
